url:
  recommendations: http://localhost:9001/generic-recommendations
  tailoredrecommendations: http://localhost:9002/tailored-recommendations

server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost/myflix?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
app:
  admin:
    username: admin
    password: admin
    authorities: ROLE_ADMIN
  authorities: ROLE_VIEWER

